### ISSUE TITLE
Add Java Program for Calculating Levenshtein Distance Between Two Strings

### ISSUE THREAD

**Issue by Rekklessss** [Ayu-hack/Hacktoberfest-Contributions#100]
I propose adding a Java implementation to calculate the Levenshtein distance between two strings using dynamic programming. The Levenshtein distance measures the similarity between two strings by determining the minimum number of single-character edits (insertions, deletions, or substitutions) needed to transform one string into the other. This metric is widely used in applications like spell checking, DNA sequence analysis, and natural language processing.

### **Implementation Details:**

 **Dynamic Programming Approach**: Constructs a matrix and fills it iteratively to determine the distance. This method has a time complexity of O(nm) and a space complexity of O(nm).

**Optimized Dynamic Programming Approach**: Utilizes an optimized matrix representation that significantly reduces the space complexity from O(nm) to O(n), where n and m are the lengths of the input strings.

### **Feature Benefits:**

Adding this program will be valuable for developers looking to implement string similarity checks or edit distance calculations in Java.

**https://en.wikipedia.org/wiki/Levenshtein_distance**

I am working towards the Hacktoberfest 2024, so it would be amazing if you could assign this issue to me.
#Hacktoberfest2024

**Comment by Ayu-hack** [comment]
Please share the screenshot of working in PR, to get it merged.
Assigned. More repos are available for pull requests, and they’re part of Hacktoberfest 2024.
Feel free to **tag me in your Hacktoberfest certificate or badges LinkedIn post**! 😄

👉 **Follow my GitHub and connect with me on** [LinkedIn](https://www.linkedin.com/in/ayush-tiwari02)!
⭐ **Star these repos** to stay updated for next year’s Hacktoberfest!
