### ISSUE TITLE
Add Java Program for RSA Encryption and Decryption

### ISSUE THREAD

**Issue by Rekklessss** [Ayu-hack/Hacktoberfest-Contributions#105]
I propose adding a Java implementation of the RSA algorithm for encryption and decryption. RSA (Rivest-Shamir-Adleman) is a widely used public-key cryptographic algorithm, commonly employed for secure data transmission. This implementation provides both encryption and decryption functionalities using generated public and private key pairs.

### **Implementation Details:**
The Java class RSA is implemented to generate a key pair consisting of a public key and a private key.
The keys are generated using two large prime numbers (p and q) and computing the modulus as their product.
The public key is chosen to be a small odd number that is co-prime to (p-1)*(q-1), and the private key is computed as the modular inverse of the public key with respect to (p-1)*(q-1).

### **Feature Benefits:**
This implementation will help developers understand and experiment with RSA encryption/decryption in Java.
It can be used as a foundational example for secure communication and digital signatures.

**https://en.wikipedia.org/wiki/RSA_(cryptosystem)**

I am working towards the Hacktoberfest 2024, so it would be amazing if you could assign this issue to me.
#Hacktoberfest2024

**Comment by Ayu-hack** [comment]
Please share the screenshot of working in PR, to get it merged.
Assigned. More repos are available for pull requests, and they’re part of Hacktoberfest 2024.
Feel free to **tag me in your Hacktoberfest certificate or badges LinkedIn post**! 😄

👉 **Follow my GitHub and connect with me on** [LinkedIn](https://www.linkedin.com/in/ayush-tiwari02)!
⭐ **Star these repos** to stay updated for next year’s Hacktoberfest!

**Comment by Ayu-hack** [comment]
⭐ Star this repos to get your PR merged faster! 🚀

**Comment by Ayu-hack** [comment]
Please consider contributing to this repo: https://github.com/Ayu-hack/Hacktoberfest2024
Sorry for the inconvenience, and thank you for your understanding! 🙏
