### ISSUE TITLE
Add Java Prpgram to find the Single Non-Duplicate Element in a Sorted Array Using Binary Search

### ISSUE THREAD

**Issue by SaurabhKumar171** [Ayu-hack/Hacktoberfest-Contributions#107]
**Detailed Explanation:**
Given a sorted array where every element appears twice except for one element that appears only once, you are tasked with finding the single non-duplicate element. The challenge is to solve this problem in O(log n) time complexity using binary search. This ensures efficiency when working with large datasets.

**Steps to Reproduce:**
1). Input a sorted array of integers, where each element except one appears exactly twice.
2). The array is sorted, and the single non-duplicate element is present exactly once.
3). Implement the binary search algorithm to find the non-duplicate element without iterating through the entire array.

**Expected Behavior:** 
The program should correctly identify and return the element that appears only once in the array, ensuring an optimized time complexity of O(log n).

Can you please assign me this issue under Hacktoberfest 2024?
#Hacktoberfest2024

**Comment by Ayu-hack** [comment]
Assigned. More repos are available for pull requests, and they’re part of Hacktoberfest 2024.
Feel free to **tag me in your Hacktoberfest certificate or badges LinkedIn post**! 😄

👉 **Follow my GitHub and connect with me on** [LinkedIn](https://www.linkedin.com/in/ayush-tiwari02)!
⭐ **Star these repos** to stay updated for next year’s Hacktoberfest!

**Comment by SaurabhKumar171** [comment]
Hey @Ayu-hack , I have submitted a pull request #108 to add a solution for finding a single non-duplicate element using binary search.

Please review it at your convenience. I appreciate your time!
