### ISSUE TITLE
Add python encryptor and decryptor

### ISSUE THREAD

**Issue by fahmid-juboraj** [Ayu-hack/Hacktoberfest-Contributions#109]
Need an implementation for the encryption and decryption algorithms implemented in python

**Comment by Ayu-hack** [comment]
Already exists. Ref issue #105 
Please bring something new n unique.
More repos are available for pull requests, and they’re part of Hacktoberfest 2024.
Feel free to **tag me in your Hacktoberfest certificate or badges LinkedIn post**! 😄
👉 **Follow my GitHub and connect with me on** [LinkedIn](https://www.linkedin.com/in/ayush-tiwari02)!
⭐ **Star these repos** to stay updated for next year’s Hacktoberfest!
