### ISSUE TITLE
Implement a FizzBuzz Algorithm to Handle Special Output for Multiples of 3 and 5

### ISSUE THREAD

**Issue by SaurabhKumar171** [Ayu-hack/Hacktoberfest-Contributions#113]
**Detailed Explanation:**
We need to create a solution to the FizzBuzz problem, a common algorithmic challenge. The program should iterate through numbers 1 to 100, performing specific actions based on the divisibility of each number. The detailed behavior is as follows:
1). For numbers divisible by 3, the program should print "Fizz" instead of the number.
2). For numbers divisible by 5, the program should print "Buzz" instead of the number.
3). For numbers divisible by both 3 and 5, the program should print "FizzBuzz."
4). If the number is not divisible by either 3 or 5, it should print the number itself.

**Expected Behavior:**
The solution should correctly identify numbers divisible by 3, 5, or both, and print the appropriate output. The program should complete without any errors and display results in the terminal or console.

Can you please assign me this issue under Hacktoberfest 2024?
#Hacktoberfest2024

**Comment by Ayu-hack** [comment]
Assigned. 
 ⭐ Star these repos to get your PR merged faster! 
 🚀 More repos are available for pull requests, and they’re part of Hacktoberfest 2024.
Feel free to tag me in your Hacktoberfest certificate or badges LinkedIn post! 😄
👉 Follow my GitHub and connect with me on [LinkedIn](https://www.linkedin.com/in/ayush-tiwari02)!
