### ISSUE TITLE
Creating a python to do app

### ISSUE THREAD

**Issue by fahmid-juboraj** [Ayu-hack/Hacktoberfest-Contributions#116]
I want to contribute with a python to do app, please assign me to contribute, i already made a PR#115

**Comment by Ayu-hack** [comment]
Assigned. 
 ⭐ Star these repos to get your PR merged faster! 
 🚀 More repos are available for pull requests, and they’re part of Hacktoberfest 2024.
Feel free to tag me in your Hacktoberfest certificate or badges LinkedIn post! 😄
👉 Follow my GitHub and connect with me on [LinkedIn](https://www.linkedin.com/in/ayush-tiwari02)!
