### ISSUE TITLE
Add a SDL2 project includes Mouse and Keyboard Events.

### ISSUE THREAD

**Issue by Suchit1938** [Ayu-hack/Hacktoberfest-Contributions#122]
For this project you must some Prerequisites

# SDL2 Project

## Prerequisites
- Install SDL2 library.

### On Windows:
1. Download SDL2 from SDL2 Downloads.
2. Extract the files and copy the `include` and `lib` folders to your project directory.
3. Add the SDL2 `lib` folder to your compiler's library path and the `include` folder to your compiler's include path.

### On macOS:
1. Install SDL2 using Homebrew:
   ```bash
   brew install sdl2

**Comment by Suchit1938** [comment]
Hi, @Ayu-hack i am currently doing projects on SDL2. I really think i can contribute to this issue. plz, assign the issue to me.

**Comment by Ayu-hack** [comment]
Please consider contributing to this repo:[ https://github.com/Ayu-hack/GeeksforGeeks-POTD-Solution](https://github.com/Ayu-hack/GeeksforGeeks-POTD-Solution)
Sorry for the inconvenience, and thank you for your understanding! 🙏

**Comment by Ayu-hack** [comment]
This repo has been falsely reported by someone so it has been excluded from hacktoberfest. we have moved to new one.
