### ISSUE TITLE
Add Greetings Bot

### ISSUE THREAD

**Issue by KiranBaliga** [Ayu-hack/Hacktoberfest-Contributions#47]
Hello! The project is missing a simple and customizable Greetings bot when someone new visits Ayu-hack project and raises a new issue or a PR. This is a level1 enhancement. Please let me know if it is okay to set this one up! 💫

#hacktoberfest

**Comment by KiranBaliga** [comment]
@Ayu-hack A single PR with two commit has been made to address code of conduct and greetings bot to your repo. Please review and action accordingly.

**Comment by Aastha7078** [comment]
Assign it to me
