### ISSUE TITLE
Add Code of Conduct

### ISSUE THREAD

**Issue by KiranBaliga** [Ayu-hack/Hacktoberfest-Contributions#48]
I would like to add a code of conduct developed for your repository. Please let me know if it is okay to proceed. Please assign to me and add hacktoberfest labels.

**Comment by Ayu-hack** [comment]
Assigned. There are more repos in which you can make pull request and for sure it will be accepted.They are also part of hacktoberfest 2024. Thank you.

**Comment by Prateek-Sarkar** [comment]
I’d like to add a Code of Conduct to the repository to help you create a positive environment. Please let me know if it’s okay to proceed.

**Comment by KiranBaliga** [comment]
@Ayu-hack I have raised a PR as per the assignment and approval. Please review and action accordingly. Thank you!

**Comment by Ayu-hack** [comment]
Done. There are more repos where you can make pull requests, and your contributions will definitely be accepted! They are also part of Hacktoberfest 2024.
Don’t forget to tag me in your LinkedIn certificate post if possible. Thank you! 😄

👉 Do follow my GitHub and connect with me on Linkedin
⭐ Also, don't forget to star these repos to stay updated for next year's Hacktoberfest!

**Comment by Ayu-hack** [comment]
Sorry brother. Reopened!
