### ISSUE TITLE
Word Break Problem

### ISSUE THREAD

**Issue by Astordnomer** [Ayu-hack/Hacktoberfest-Contributions#51]
hi i wont to make Word Break Problem if a given string can be segmented into a space-separated sequence of dictionary words.
Can you Assign me.

**Comment by Ayu-hack** [comment]
Assigned. There are more repos where you can make pull requests, and your contributions will definitely be accepted! They are also part of Hacktoberfest 2024.
Don’t forget to tag me in your LinkedIn certificate post if possible. Thank you! 😄

**Comment by Aastha7078** [comment]
please assign this to me
