### ISSUE TITLE
Add contributor.md

### ISSUE THREAD

**Issue by kartikey369-ind** [Ayu-hack/Hacktoberfest-Contributions#52]
How about creating contributor.md so that we could list out every one

**Comment by Ayu-hack** [comment]
Assigned. There are more repos where you can make pull requests, and your contributions will definitely be accepted! They are also part of Hacktoberfest 2024.
Don’t forget to tag me in your LinkedIn certificate post if possible. Thank you! 😄

👉 Do follow my GitHub and connect with me on LinkedIn
⭐ Also, don't forget to star these repos to stay updated for next year's Hacktoberfest!

**Comment by kartikey369-ind** [comment]
Hi could you please check my pull request 

https://github.com/Ayu-hack/Hacktoberfest-Contributions/pull/53

**Comment by codebydeep** [comment]
Hey @Ayu-hack, could you please assign this issue to me?

**Comment by Ayu-hack** [comment]
@codebydeep no this is not a issue. Please find something new n unique. 
More repos are available for pull requests, and they’re part of Hacktoberfest 2024.
Feel free to **tag me in your Hacktoberfest certificate or badges LinkedIn post**! 😄

👉 **Follow my GitHub and connect with me on** [LinkedIn](https://www.linkedin.com/in/ayush-tiwari02)!
⭐ **Star these repos** to stay updated for next year’s Hacktoberfest!

**Comment by Ayu-hack** [comment]
Please consider contributing to this repo: https://github.com/Ayu-hack/Hacktoberfest2024
Sorry for the inconvenience, and thank you for your understanding! 🙏
