### ISSUE TITLE
Finding HCF of two numbers using Euclid's Algorithm

### ISSUE THREAD

**Issue by Virat-Shrimali** [Ayu-hack/Hacktoberfest-Contributions#54]
Problem Statement:
Write a Java program to find the HCF (also known as GCD - Greatest Common Divisor) of two numbers.

Can you please assign me this issue under Hacktoberfest 2024?

**Comment by Ayu-hack** [comment]
Assigned. There are more repos where you can make pull requests, and your contributions will definitely be accepted! They are also part of Hacktoberfest 2024.
Don’t forget to tag me in your LinkedIn certificate post if possible. Thank you! 😄

👉 Do follow my GitHub and connect with me on LinkedIn
⭐ Also, don't forget to star these repos to stay updated for next year's Hacktoberfest!

**Comment by Aastha7078** [comment]
assign it to me
