### ISSUE TITLE
Solve the Coin change problem Using Memorization

### ISSUE THREAD

**Issue by sshaikshoaib** [Ayu-hack/Hacktoberfest-Contributions#55]
You are given an integer array coins representing coins of different denominations and an integer amount representing a total amount of money.

Return the fewest number of coins that you need to make up that amount. If that amount of money cannot be made up by any combination of the coins, return -1.

You may assume that you have an infinite number of each kind of coin.

 

Example 1:

Input: coins = [1,2,5], amount = 11
Output: 3
Explanation: 11 = 5 + 5 + 1
Example 2:

Input: coins = [2], amount = 3
Output: -1
Example 3:

Input: coins = [1], amount = 0
Output: 0
 

Constraints:

1 <= coins.length <= 12
1 <= coins[i] <= 231 - 1
0 <= amount <= 104

**Comment by DheerajKumar20104** [comment]
Hey! @sshaikshoaib ,Can you assign me this issue?

**Comment by Ayu-hack** [comment]
Assigned. There are more repos where you can make pull requests, and your contributions will definitely be accepted! They are also part of Hacktoberfest 2024.
Don’t forget to tag me in your LinkedIn certificate post if possible. Thank you! 😄

👉 Do follow my GitHub and connect with me on LinkedIn
⭐ Also, don't forget to star these repos to stay updated for next year's Hacktoberfest!
