### ISSUE TITLE
Java Stream Api Coding Interview Question

### ISSUE THREAD

**Issue by Spardha-hash** [Ayu-hack/Hacktoberfest-Contributions#60]
How to find duplicate elements in a given integers list in java using Stream functions?

Input 1 :
arr[] = [10,15,8,49,25,98,98,32,15]
Output : 98, 15

Input 2 :
arr[] = [1, 1, 85, 6, 2, 3, 65, 6, 45, 45, 5662, 2582, 2, 266, 666, 656]
Output : 1 6 2 45

Hi @Ayu-hack ,
This was one of the question that was asked to me in Interview. I am raising the issue for it to add this in your respository. Please assign this issue to me.

**Comment by Ayu-hack** [comment]
Assigned. There are more repos where you can make pull requests, and your contributions will definitely be accepted! They are also part of Hacktoberfest 2024.
Don’t forget to tag me in your LinkedIn certificate post if possible. Thank you! 😄

👉 Do follow my GitHub and connect with me on [LinkedIn](https://www.linkedin.com/in/ayush-tiwari02)!
⭐ Also, don't forget to star these repos to stay updated for next year's Hacktoberfest!
