### ISSUE TITLE
Added two new files #HungmanGame and #PasswordGenerator

### ISSUE THREAD

**Issue by ishubtripathi** [Ayu-hack/Hacktoberfest-Contributions#65]
# Pull Request: Password Generator and Hangman Game Projects

## Overview
This pull request introduces two engaging Java projects: a **Password Generator** and a **Hangman Game**. Both programs aim to enhance users' programming skills and provide fun, interactive experiences.

### 1. Password Generator

- **Description**: A simple yet effective password generator that allows users to create secure passwords based on customizable criteria.
- **Features**:
  - **Customizable Length**: Users can specify the desired length of the generated password.
  - **Character Set Options**: Users can choose to include:
    - Uppercase letters
    - Lowercase letters
    - Numbers
    - Special symbols
  - **Secure Random Generation**: Utilizes `SecureRandom` for generating random characters, ensuring better security compared to basic random functions.
- **Usage**:
  1. Compile the Java file using `javac PasswordGenerator.java`.
  2. Run the program with `java PasswordGenerator`.
  3. Follow the prompts to specify your password criteria.
- **Future Improvements**:
  - Validation to ensure at least one character type is selected.
  - Options for minimum character types to enhance security.
  - A graphical user interface for better user experience.

### 2. Hangman Game

- **Description**: A text-based implementation of the classic Hangman game where players guess letters of a hidden word within a limited number of attempts.
- **Features**:
  - **Random Word Selection**: The game randomly selects a word from a predefined list.
  - **User Interaction**: Players guess letters and receive feedback on their guesses.
  - **Attempts Tracking**: The game tracks the number of attempts left, adding a challenge.
- **Usage**:
  1. Compile the Java file using `javac HangmanGame.java`.
  2. Run the program with `java HangmanGame`.
  3. Follow the prompts to guess letters and reveal the hidden word.
- **Future Improvements**:
  - A larger list of words or integration of an API for word selection.
  - A scoring system or leaderboard.
  - Enhanced user interface, possibly graphical.

@Ayu-hack @ayu-hack02  Can you please assign me this issue under Hacktoberfest 2024?

**Comment by Ayu-hack** [comment]
Assigned. There are more repos where you can make pull requests, and your contributions will definitely be accepted! They are also part of Hacktoberfest 2024.
Don’t forget to tag me in your LinkedIn certificate post if possible. Thank you! 😄

👉 Do follow my GitHub and connect with me on [LinkedIn](https://www.linkedin.com/in/ayush-tiwari02)!
⭐ Also, don't forget to star these repos to stay updated for next year's Hacktoberfest!

**Comment by ishubtripathi** [comment]
sure
