### ISSUE TITLE
Missing and Repeating numbers in an array

### ISSUE THREAD

**Issue by Spardha-hash** [Ayu-hack/Hacktoberfest-Contributions#68]
Hi @Ayu-hack ,
I want to add the code for finding the missing and repeating numbers from an unsorted array. Please assign this issue to me.

**Comment by Ayu-hack** [comment]
Assigned. There are more repos where you can make pull requests, and your contributions will definitely be accepted! They are also part of Hacktoberfest 2024.
Don’t forget to tag me in your LinkedIn certificate post if possible. Thank you! 😄

👉 Do follow my GitHub and connect with me on [LinkedIn](https://www.linkedin.com/in/ayush-tiwari02)!
⭐ Also, don't forget to star these repos to stay updated for next year's Hacktoberfest!

**Comment by AnuskaKuila7811** [comment]
Hi @Ayu-hack ,
I want to add the code for finding the missing and repeating numbers from an unsorted array. Please assign this issue to me.

**Comment by AnuskaKuila7811** [comment]
Hlo i am Anuska Kuila.... I modify a file ...pls merge
