### ISSUE TITLE
Want to add a Word Counter GUI application 

### ISSUE THREAD

**Issue by solanki03** [Ayu-hack/Hacktoberfest-Contributions#73]
Word Counter GUI Application in Java
This engaging Java GUI application, named "Word Counter☆," is a user-friendly tool designed to count words and characters in a given text. The GUI is not just functional but also visually appealing, featuring a sleek design with a touch of vibrant colors. 🌈

Features 
Attractive Design :
The GUI boasts a modern design with a primary color scheme that is easy on the eyes. The subtle blend of blues and purples creates a pleasant ambiance, enhancing the user's overall experience.

Interactive Components :
The application includes various interactive components strategically placed for user convenience. These components include a logo, a title label, a text area for input, and buttons for counting and clearing.

User-Friendly Interface :
The interface is thoughtfully designed to be user-friendly. The layout is well-organized, ensuring that users can intuitively navigate through the application without any confusion.

Counting Functionality :
The "Count" button triggers the backend functionality, implemented in the CountWords class. This class utilizes a JTextArea to capture user input, counts the number of words and characters, and then displays the results in dedicated text fields.

Clearing Functionality :
To provide a seamless experience, the application includes a "Clear" button. Clicking this button invokes the clearing method from the CountWords class, ensuring a quick reset of the text area and result fields.

Dynamic Display :
The application dynamically displays the total number of words and characters in designated text boxes. The use of vibrant colors for text ensures that the results stand out against the background.

How It Works :
Input Text: Users can input their text in the spacious text area provided.
Count Button: Clicking the "Count" button triggers the word and character-counting process.
Clear Button: The "Clear" button swiftly resets the input area and result fields, providing a clean slate for the next input. 🔄

@Ayu-hack  @ayu-hack02  Can you please assign me this issue under Hacktoberfest 2024?

**Comment by Ayu-hack** [comment]
Assigned. There are more repos where you can make pull requests, and your contributions will definitely be accepted! They are also part of Hacktoberfest 2024.
Don’t forget to tag me in your LinkedIn certificate post if possible. Thank you! 😄

👉 Do follow my GitHub and connect with me on [LinkedIn](https://www.linkedin.com/in/ayush-tiwari02)!
⭐ Also, don't forget to star these repos to stay updated for next year's Hacktoberfest!
