### ISSUE TITLE
Convert a List of objects into a Map by considering duplicated keys and store them in sorted order using stream api

### ISSUE THREAD

**Issue by Spardha-hash** [Ayu-hack/Hacktoberfest-Contributions#78]
Hi @Ayu-hack ,
I want to add the below java stream api interview question.

Convert a List of objects into a Map by considering duplicated keys and store them in sorted order.
Example - 
List<Notes> noteLst = new ArrayList<>();
    noteLst.add(new Notes(1, "note1", 11));
    noteLst.add(new Notes(2, "note2", 22));
    noteLst.add(new Notes(3, "note3", 33));
    noteLst.add(new Notes(4, "note4", 44));
    noteLst.add(new Notes(5, "note5", 55));
    noteLst.add(newNotes(6, "note4",66));

Output - 
{note1=11, note2=22, note3=33, note4=44, note5=55}

Please assign this issue to me.

**Comment by Ayu-hack** [comment]
1. Assigned.
2. Before submitting PR check that it shouldn't already exists in repo and do share the screenshot of working code. 

There are more repos where you can make pull requests, and your contributions will definitely be accepted! They are also part of Hacktoberfest 2024.
Don’t forget to tag me in your LinkedIn certificate post if possible. Thank you! 😄

👉 Do follow my GitHub and connect with me on [LinkedIn](https://www.linkedin.com/in/ayush-tiwari02)!
⭐ Also, don't forget to star these repos to stay updated for next year's Hacktoberfest!
