### ISSUE TITLE
Solve Remove Nth Node From End of Linked List in Java in O(n)

### ISSUE THREAD

**Issue by sundarrr** [Ayu-hack/Hacktoberfest-Contributions#87]

**Comment by Ayu-hack** [comment]
I saw your profile you have expert knowledge of MongoDB. There is a project repo named"Restaurant Management System" there is an issue with database we have used mysql but you can replace with mongoDB. If possible then try to fix. That project is also part of hacktoberfest 2024.

Assigned. More repos are available for pull requests, and they’re part of Hacktoberfest 2024.
Feel free to **tag me in your Hacktoberfest certificate or badges LinkedIn post**! 😄
👉 **Follow my GitHub and connect with me on** [LinkedIn](https://www.linkedin.com/in/ayush-tiwari02)!
⭐ **Star these repos** to stay updated for next year’s Hacktoberfest!

**Comment by sundarrr** [comment]
Yeah Sure. I will check that.
