### ISSUE TITLE
File Version Control Using Hashing

### ISSUE THREAD

**Issue by pratikj697** [Ayu-hack/Hacktoberfest-Contributions#93]
Create a Python program that simulates a simple version control system using file hashing. The goal is to maintain a version history of files where changes in file content are tracked, and only the modified files are added to the new version. Files with unchanged content (same hash) will not be duplicated.

Requirements:
1. File Hashing:
For each file, compute a SHA-256 hash to determine whether the file content has changed since the last version.
2. Version Control:
Maintain a history of file versions. Only store a new version of a file if its content has changed (i.e., if the hash is different from the last version).
3. Handling Missing Files:
If a file does not exist, skip it and log the error.

Version Display:
Implement a feature to display the stored versions of files.

Can you please assign this task to me under HacktoberFest 2024 @Ayu-hack.

**Comment by Ayu-hack** [comment]
Please share the screenshot in PR
Assigned. More repos are available for pull requests, and they’re part of Hacktoberfest 2024.
Feel free to **tag me in your Hacktoberfest certificate or badges LinkedIn post**! 😄

👉 **Follow my GitHub and connect with me on** [LinkedIn](https://www.linkedin.com/in/ayush-tiwari02)!
⭐ **Star these repos** to stay updated for next year’s Hacktoberfest!

**Comment by Ayu-hack** [comment]
⭐ Please star this repo as a token of appreciation for the efforts! 🙌
