### ISSUE TITLE
Number guessing game in java

### ISSUE THREAD

**Issue by Jaid101** [Ayu-hack/Hacktoberfest-Contributions#95]
Assign me this issue I can add the Number guessing game in java

**Comment by Ayu-hack** [comment]
Already exists. Bring something new n unique.
More repos are available for pull requests, and they’re part of Hacktoberfest 2024.
Feel free to **tag me in your Hacktoberfest certificate or badges LinkedIn post**! 😄
👉 **Follow my GitHub and connect with me on** [LinkedIn](https://www.linkedin.com/in/ayush-tiwari02)!
⭐ **Star these repos** to stay updated for next year’s Hacktoberfest!
