### ISSUE TITLE
Add Java Program for Determining the nth Catalan Number

### ISSUE THREAD

**Issue by Rekklessss** [Ayu-hack/Hacktoberfest-Contributions#99]
I propose adding a Java implementation to compute the nth Catalan number using dynamic programming. The Catalan numbers are a sequence of natural numbers that have significant applications in combinatorics, particularly in counting problems like binary trees, expressions with balanced parentheses, and more. The program aims to efficiently calculate the nth Catalan number with a time complexity of O(n²) and space complexity of O(n).

### **Implementation Details:**
The Java program employs dynamic programming to compute the Catalan numbers, with an array to store intermediate results.

### **Feature Benefits:**

This program provides a simple and efficient way to compute the Catalan numbers up to the 50th term.
It will be a useful addition for those interested in learning dynamic programming techniques for combinatorial mathematics.

**https://en.wikipedia.org/wiki/Catalan_number**

I am working towards the Hacktoberfest 2024, so it would be amazing if you could assign this issue to me.
#Hacktoberfest2024

**Comment by Ayu-hack** [comment]
Please share the screenshot of working in PR, to get it merged.
Assigned. More repos are available for pull requests, and they’re part of Hacktoberfest 2024.
Feel free to **tag me in your Hacktoberfest certificate or badges LinkedIn post**! 😄

👉 **Follow my GitHub and connect with me on** [LinkedIn](https://www.linkedin.com/in/ayush-tiwari02)!
⭐ **Star these repos** to stay updated for next year’s Hacktoberfest!

**Comment by Ayu-hack** [comment]
Please consider contributing to this repo:[ https://github.com/Ayu-hack/GeeksforGeeks-POTD-Solution](https://github.com/Ayu-hack/GeeksforGeeks-POTD-Solution)
Sorry for the inconvenience, and thank you for your understanding! 🙏
